version: "3.9"

services:
  bot:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
    ports:
      - "8192:8192"